{{- if not .Values.defectDojo.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trivy-operator-defectdojo-importer.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-operator-defectdojo-importer.labels" . | nindent 4 }}
type: Opaque
stringData:
  DEFECT_DOJO_API_KEY: {{ required "defectDojo.apiKey is required unless defectDojo.existingSecret is set" .Values.defectDojo.apiKey | quote }}
{{- end }}
